### ISSUE TITLE
Helicopter respawn

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [EngineerWAK/WMS_DFO_Standalone#1]
Very good mission, but if my helicopter is destroyed during the mission, is there any way to regenerate a helicopter in DFO?

**Comment by EngineerWAK** [comment]
Thanks!
Nope, the Chopper you get when you call a mission won't respawn, however, a "permanent chopper" should be present somewhere at least at DFO Main Base, this one will respawn every time it's destroyed (if you are using one of the exemples).

**Comment by EngineerWAK** [comment]
v1.09 solve your problem :)
if WMS_DFO_CreateChopper = true; (by default in exemples), 
5 seconds after destruction: blue smoke at the original chopper position (DFO Base probably), 
25 seconds later: same chopper (classename), (empty inventory) at the blue smoke.
Not tested on dedicated server yet.

**Comment by ZHANGTIANYAO1** [comment]
Thanks!
