### ISSUE TITLE
Function- add refresh botton

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [EngineerWAK/WMS_DFO_Standalone#2]
Can add a refresh feature that lets the player abandon the current mission and apply for a new one to prevent special situations from happening？

**Comment by EngineerWAK** [comment]
You can run 3 missions at the time (or more if you change WMS_DFO_MaxRunning = 3) and you have no punishment if you don't finish one so just call a new mission and let the previous one time out.
The time out is WMS_DFO_Timer = 1800;
And the cooldown before you can call a new mission WMS_DFO_CoolDown = 600;

**Comment by ZHANGTIANYAO1** [comment]
Thanks
