### ISSUE TITLE
exclusion areas

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [EngineerWAK/WMS_DFO_Standalone#3]
Is there a way to add exclusion areas so that tasks don't spawn in a specific area?

**Comment by EngineerWAK** [comment]
I keep this one in mind for later update but not for now.

**Comment by ZHANGTIANYAO1** [comment]
thanks

**Comment by EngineerWAK** [comment]
Done!
untested yet but it should do the job.
WMS_DFO_ExclusionZone = []; //[[[x,y,z],radius],[[x,y,z],radius],[[x,y,z],radius],[[x,y,z],radius]]; will work for "random" and "sea" spawns, not for forests/locals/bases or others
