### ISSUE TITLE
Version1.10 will break H-60 interaction on dedicated server

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [EngineerWAK/WMS_DFO_Standalone#4]
Version1.10 will break H-60 interaction on the dedicated server but version 1.09 works well.

**Comment by EngineerWAK** [comment]
Wait, what ? :D
Aren't we at v1.11 or something on github?
I didn't change anything for weeks, I'm working on a custom map for Reforger and it's very time consuming.
what is broken exactly?
I'll try to find some time for the exclusion zone too...
[Edit] I have a v1.12 that I didn't upload but I don't remember any problem with interaction before that.

**Comment by ZHANGTIANYAO1** [comment]
The last version of example pbo missions are still v1.10, When I upload those missions on a dedicated server I find out that when I press F for MFD bezel keys, nothing happened. same for FMS.

**Comment by EngineerWAK** [comment]
Ok, I'll fire up a box with a dedi on it to check, from the mission editor I don't see any problems with v1.10 or v1.12

**Comment by EngineerWAK** [comment]
well, this is the test:
https://youtu.be/pd4PbI58daE
v1.12, packing now, let me know if it's still messing with your interactions.

**Comment by ZHANGTIANYAO1** [comment]
I think it still messing with my interactions. I check my server log and find this
User XXX tried to remoteExec a disabled function
Scripting function 'vtx_uh60_fms_fnc_interaction_p...' is not allowed to be remotely executed
It seems that my interactions are blocked by something. Do you know how to fix this?

**Comment by EngineerWAK** [comment]
ok so that's not a DFO problem :D
yes, hatchet use a lot of remoteExec, you have to white list them like this:
https://github.com/EngineerWAK/WMS_TheLastCartridges/blob/main/Framework/CfgRemoteExec.hpp
or allow all remoteExec like that:
```
class CfgRemoteExec
{
	class Functions
	{
		mode = 2; //0: no remoteExec, 1: white liste, 2: all autorized
		jip = 0;
	};
	class Commands
	{
		mode=0;
		jip=0;
	};
};
```
I will add it so it should solve the problem for everybody.

**Comment by ZHANGTIANYAO1** [comment]
Thanks

**Comment by ZHANGTIANYAO1** [comment]
It works!!! Thanks!!! So strange because I never had this porblem in other missions. But thanks again to fix it!
